services:
  bot:
    container_name: the-bot
    env_file:
      - ./.env
    build: .
    ports:
      - 8088:8088
    volumes:
      - .:/bot
    command: python3 ./src/main.py
    restart: always
  